name: gitleaks

on:
  pull_request: {}
  push:
    branches:
    - main
    - master
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: security-gitleaks-config
      uses: actions/checkout@v2
      with:
        repository: alangonzalez/gitleaks-global-config
    - run: |
        ls -ltr *
    - uses: actions/checkout@v1
    - run: |
        ls -ltr *
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
      with:
        config-path: security/gitleaks.global.toml
